ignoredBuiltDependencies:
  - lmdb
  - msgpackr-extract
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - nx

overrides:
  '@angular/platform-server@>=20.0.0-next.0 <20.3.0': '>=20.3.0'
  '@angular/ssr@>=20.0.0-next.0 <20.3.0': '>=20.3.0'
  '@modelcontextprotocol/sdk@<1.24.0': '>=1.24.0'
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  koa@>=2.0.0 <2.16.2: '>=2.16.2'
  koa@>=3.0.0-alpha.0 <3.0.1: '>=3.0.1'
  koa@>=3.0.1 <3.0.3: '>=3.0.3'
  on-headers@<1.1.0: '>=1.1.0'
  playwright@<1.55.1: '>=1.55.1'
  tmp@<=0.2.3: '>=0.2.4'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
