overrides:
  '@angular/platform-server@>=20.0.0-next.0 <20.3.0': '>=20.3.0'
  '@angular/ssr@>=20.0.0-next.0 <20.3.0': '>=20.3.0'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  koa@>=2.0.0 <2.16.2: '>=2.16.2'
  koa@>=3.0.0-alpha.0 <3.0.1: '>=3.0.1'
  on-headers@<1.1.0: '>=1.1.0'
  tmp@<=0.2.3: '>=0.2.4'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'
